name: stellar_flutter_sdk
description: A Stellar SDK for Flutter, that can query Horizon and Soroban RPC, build, signs and submit transactions to Stellar. Supports many SEPs and can deploy and invoke Soroban Contracts.
version: 3.0.1
homepage: https://github.com/Soneso/stellar_flutter_sdk

platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.16.0
  crypto: ^3.0.6
  http: ^1.5.0
  collection: ^1.18.0
  toml: ^0.17.0
  pointycastle: ^4.0.0
  unorm_dart: ^0.3.1+1
  decimal: ^3.2.4
  pinenacl: ^0.6.0
  convert: ^3.1.2
  http_parser: ^4.0.2
  dio: ^5.9.0
  archive: ^3.6.1

flutter:
  assets:
    - test/wasm/

dev_dependencies:
  flutter_test:
    sdk: flutter
