name: stellar_flutter_sdk
description: A stellar blockchain sdk that query's horizon, build, signs and submits transactions to the stellar network.
version: 1.7.6
homepage: https://github.com/Soneso/stellar_flutter_sdk

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  fixnum: ^1.0.1
  http: ^1.0.0
  collection: ^1.15.0
  toml: ^0.13.1
  pointycastle: ^3.6.2
  unorm_dart: ^0.2.0
  decimal: ^2.3.0
  pinenacl: ^0.5.1
  convert: ^3.0.2
  http_parser: ^4.0.1
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
