name: stellar_flutter_sdk
description: A stellar blockchain sdk that query's horizon, build, signs and submits transactions to the stellar network.
version: 1.2.2
homepage: https://github.com/Soneso/stellar_flutter_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.1
  fixnum: ^1.0.0
  http: ^0.13.3
  collection: ^1.15.0
  toml: ^0.11.0
  pointycastle: ^3.3.1
  unorm_dart: ^0.2.0
  decimal: ^1.3.0
  pinenacl: ^0.3.3
  convert: ^3.0.1
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
