name: stellar_flutter_sdk
description: A stellar blockchain sdk that query's horizon, build, signs and submits transactions to the stellar network.
version: 1.9.0-beta
homepage: https://github.com/Soneso/stellar_flutter_sdk

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  fixnum: ^1.1.0
  http: ^1.2.1
  collection: ^1.18.0
  toml: ^0.16.0
  pointycastle: ^3.9.1
  unorm_dart: ^0.3.0
  decimal: ^3.0.2
  pinenacl: ^0.6.0
  convert: ^3.1.1
  http_parser: ^4.0.2
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
