blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Feedback & Discussions
    url: https://github.com/Soneso/stellar_flutter_sdk/discussions
    about: For open-ended questions, ideas, or general feedback, please use Discussions.

